In [1]:
from fan_autoencoder import FanVariationalAutoEncoder
import tensorflow as tf

In [2]:
(encoder, decoder, autoencoder) = FanVariationalAutoEncoder.build(is_compiled=False)

In [8]:
encoder.summary()

Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
encoder_input (InputLayer)      [(None, 28, 28, 1)]  0                                            
__________________________________________________________________________________________________
flatten (Flatten)               (None, 784)          0           encoder_input[0][0]              
__________________________________________________________________________________________________
dense (Dense)                   (None, 256)          200960      flatten[0][0]                    
__________________________________________________________________________________________________
z_mean (Dense)                  (None, 32)           8224        dense[0][0]                      
____________________________________________________________________________________________

In [9]:
decoder.summary()

Model: "decoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
z_sampling (InputLayer)      [(None, 32)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 256)               8448      
_________________________________________________________________
dense_2 (Dense)              (None, 784)               201488    
_________________________________________________________________
reshape (Reshape)            (None, 28, 28, 1)         0         
Total params: 209,936
Trainable params: 209,936
Non-trainable params: 0
_________________________________________________________________


In [6]:
autoencoder.summary()

Model: "vae"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
encoder_input (InputLayer)      [(None, 28, 28, 1)]  0                                            
__________________________________________________________________________________________________
encoder (Model)                 [(None, 32), (None,  217408      encoder_input[0][0]              
__________________________________________________________________________________________________
decoder (Model)                 (None, 28, 28, 1)    209936      encoder[1][2]                    
__________________________________________________________________________________________________
tf_op_layer_SquaredDifference ( [(None, 28, 28, 1)]  0           decoder[1][0]                    
                                                                 encoder_input[0][0]            

In [19]:
((trainX, _), (testX, _)) = tf.keras.datasets.mnist.load_data()

# add a channel dimension to every image in the dataset, then scale
# the pixel intensities to the range [0, 1]
trainX = np.expand_dims(trainX, axis=-1)  # (sample,w,h) -> (sample, w, h, d)
testX = np.expand_dims(testX, axis=-1)

trainX = trainX.astype("float32") / 255.0
testX = testX.astype("float32") / 255.0

train_data = tf.data.Dataset.from_tensor_slices((trainX, trainX))
train_data = train_data.shuffle(5000).batch(64)

test_data = tf.data.Dataset.from_tensor_slices((testX,testX))
test_data = test_data.shuffle(5000).batch(64)

In [13]:
# trainX.shape # (60000, 28, 28, 1)
testX.shape # (10000, 28, 28, 1)

(10000, 28, 28, 1)

In [21]:
H = autoencoder.fit(
    train_data,
    validation_data=test_data,
    epochs=10)

Train for 938 steps, validate for 157 steps
Epoch 1/10
938/938 [==============================] - 11s 12ms/step - loss: 0.0714 - val_loss: 0.0680
Epoch 2/10
938/938 [==============================] - 10s 11ms/step - loss: 0.0677 - val_loss: 0.0679
Epoch 3/10
938/938 [==============================] - 10s 11ms/step - loss: 0.0676 - val_loss: 0.0678
Epoch 4/10
938/938 [==============================] - 10s 11ms/step - loss: 0.0675 - val_loss: 0.0677
Epoch 5/10
938/938 [==============================] - 10s 11ms/step - loss: 0.0675 - val_loss: 0.0678
Epoch 6/10
938/938 [==============================] - 10s 11ms/step - loss: 0.0674 - val_loss: 0.0677
Epoch 7/10
938/938 [==============================] - 10s 11ms/step - loss: 0.0674 - val_loss: 0.0678
Epoch 8/10
938/938 [==============================] - 10s 11ms/step - loss: 0.0674 - val_loss: 0.0677
Epoch 9/10
938/938 [==============================] - 10s 11ms/step - loss: 0.0674 - val_loss: 0.0677
Epoch 10/10
938/938 [=================

In [17]:
H = autoencoder.fit(
    trainX, trainX,
    validation_data=(testX, testX),
    epochs=10,
    batch_size=64)

ValueError: ('Error when checking model target: expected no data, but got:', array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       ...,


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]]], dtype=float32))

In [3]:
x = tf.constant([[1., 1.], [2., 2.]])
tf.reduce_mean(x)  # 1.5


<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

In [4]:
tf.reduce_mean(x, 0)  # [1.5, 1.5]


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 1.5], dtype=float32)>

In [5]:
tf.reduce_mean(x, 1)  # [1.,  2.]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [13]:
mse = tf.keras.losses.MeanSquaredError()

In [14]:
loss = mse([0., 0., 1., 1.], [1., 1., 1., 0.])
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.75>