In [1]:
import pandas as pd

# reshape with pivot_table(long to wide)

![pandas_reshape](img/panda_reshape_pivot_table.png)

*  https://towardsdatascience.com/reshape-pandas-dataframe-with-pivot-table-in-python-tutorial-and-visualization-2248c2012a31
*  https://towardsdatascience.com/reshape-pandas-dataframe-with-melt-in-python-tutorial-and-visualization-29ec1450bb02
*  https://beta.deepnote.com/project/d1350ad6-bcb4-4c3d-857b-c29d01b8a803#%2Fpivot_table.ipynb

*  https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b

## create data
deepnote

https://beta.deepnote.com/project/d1350ad6-bcb4-4c3d-857b-c29d01b8a803#%2Fpivot_table.ipynb

In [2]:
df_long = pd.DataFrame({
        "student":
            ["Andy", "Bernie", "Cindy", "Deb",
             "Andy", "Bernie", "Cindy", "Deb",
             "Andy", "Bernie", "Cindy", "Deb"],
        "school":
            ["Z", "Y", "Z", "Y",
             "Z", "Y", "Z", "Y",
             "Z", "Y", "Z", "Y"],
        "class":
            ["english", "english", "english", "english",
             "math", "math", "math", "math",
             "physics", "physics", "physics", "physics"],
        "grade":
            [10, 100, 1000, 10000,
             20, 200, 2000, 20000,
             30, 300, 3000, 30000]
})

In [3]:
df_long.head(12)

student school    class  grade
0     Andy      Z  english     10
1   Bernie      Y  english    100
2    Cindy      Z  english   1000
3      Deb      Y  english  10000
4     Andy      Z     math     20
5   Bernie      Y     math    200
6    Cindy      Z     math   2000
7      Deb      Y     math  20000
8     Andy      Z  physics     30
9   Bernie      Y  physics    300
10   Cindy      Z  physics   3000
11     Deb      Y  physics  30000

## Pivot example 1(columns, values)

In [5]:
df_long.pivot_table(index=["student", "school"], 
                    columns='class', 
                    values='grade')

class           english   math  physics
student school                         
Andy    Z            10     20       30
Bernie  Y           100    200      300
Cindy   Z          1000   2000     3000
Deb     Y         10000  20000    30000

In [6]:
df_long.pivot_table(index=["student", "school"], 
                    columns='class', 
                    values='grade').reset_index()

class student school  english   math  physics
0        Andy      Z       10     20       30
1      Bernie      Y      100    200      300
2       Cindy      Z     1000   2000     3000
3         Deb      Y    10000  20000    30000

## Pivot Example 2(margines = True )

In [7]:
df_long.pivot_table(index=["student", "school"], 
                    columns='class', 
                    values='grade',
                    margins=True,
                    aggfunc='sum').reset_index()

class student school  english   math  physics    All
0        Andy      Z       10     20       30     60
1      Bernie      Y      100    200      300    600
2       Cindy      Z     1000   2000     3000   6000
3         Deb      Y    10000  20000    30000  60000
4         All           11110  22220    33330  66660

## Pivot example 3 ( vs groupby, aggfunc)


In [8]:
df_long.pivot_table(index=["student", "school"]).reset_index()

student school  grade
0    Andy      Z     20
1  Bernie      Y    200
2   Cindy      Z   2000
3     Deb      Y  20000

In [9]:
df_long.groupby(['student', 'school']).mean().reset_index()

student school  grade
0    Andy      Z     20
1  Bernie      Y    200
2   Cindy      Z   2000
3     Deb      Y  20000

In [10]:
df_long.pivot_table(index=["student", "school"], 
                    aggfunc=['max', 'first'])

max           first       
                  class  grade    class  grade
student school                                
Andy    Z       physics     30  english     10
Bernie  Y       physics    300  english    100
Cindy   Z       physics   3000  english   1000
Deb     Y       physics  30000  english  10000

In [11]:
df_long.groupby(["student", "school"]).agg(['max', 'first'])

class           grade       
                    max    first    max  first
student school                                
Andy    Z       physics  english     30     10
Bernie  Y       physics  english    300    100
Cindy   Z       physics  english   3000   1000
Deb     Y       physics  english  30000  10000

## Pivot example 4 (columns = 2, fill_value)


In [12]:
df_long.pivot_table(index="student", 
                    columns=['school', 'class'], 
                    values='grade')

school         Y                         Z                
class    english     math  physics english    math physics
student                                                   
Andy         NaN      NaN      NaN    10.0    20.0    30.0
Bernie     100.0    200.0    300.0     NaN     NaN     NaN
Cindy        NaN      NaN      NaN  1000.0  2000.0  3000.0
Deb      10000.0  20000.0  30000.0     NaN     NaN     NaN

In [13]:
df_long.pivot_table(index="student", 
                    columns=['school', 'class'], 
                    values='grade', 
                    fill_value=-5)

school        Y                      Z              
class   english   math physics english  math physics
student                                             
Andy         -5     -5      -5      10    20      30
Bernie      100    200     300      -5    -5      -5
Cindy        -5     -5      -5    1000  2000    3000
Deb       10000  20000   30000      -5    -5      -5

# numpy reshape and stack cheatsheet

*  https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b
*  https://jalammar.github.io/visual-numpy/ 

## create numpy array

In [14]:
import numpy as np
a1 = np.arange(1, 13)  # numbers 1 to 12
print(a1.shape)
# > (12,)
print(a1)
# > [ 1  2  3  4  5  6  7  8  9 10 11 12]

(12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Reshape with reshape() method


* -1 表示自动推导剩余的尺寸/长度

In [15]:
a1_2d = a1.reshape(3, 4)  # 3_4
print(a1_2d.shape)
# > (3, 4)
print(a1_2d)
# > [[ 1  2  3  4]
#    [ 5  6  7  8]
#    [ 9 10 11 12]]

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
a1.reshape(3, 4)
a1.reshape(-1, 4)  # same as above: a1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a1.reshape(3, 4)
a1.reshape(3, -1)  # same as above: a1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a1.reshape(2, 6)
a1.reshape(2, -1)  # same as above: a1.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## Reshape along different dimensions


默认情况下，reshape（）沿第0维（行）对数组进行整形。

In [20]:
a1.reshape(3, 4) # reshapes or ‘fills in’ row by row
a1.reshape(3, 4, order='C') # same results as above

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
a1.reshape(3, 4, order='F')  # reshapes column by column


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [22]:
print(a1)  # what's the shape?
# > [ 1  2  3  4  5  6  7  8  9 10 11 12]
print(a1.shape)
# > (12,)
a1_1_by_12 = a1.reshape(1, -1)  # reshape to 1_12
print(a1_1_by_12)  # note the double square brackets!
# > [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
print(a1_1_by_12.shape)  # 1_12 array
# > (1, 12)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)


## Flatten/ravel to 1D arrays with ravel()


![title](img/reshape_ravel.png)


In [23]:
print(a1_2d)  # 3_4
# > [[ 1  2  3  4]
#    [ 5  6  7  8]
#    [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
print(a1_2d.ravel())  # ravel by row (default order='C')
# > [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
print(a1_2d.ravel(order='F'))  # ravel by column
# > [ 1  5  9  2  6 10  3  7 11  4  8 12]


[ 1  5  9  2  6 10  3  7 11  4  8 12]


## Concatenate/stack arrays with np.stack() and np.hstack()

![np_stack](img/np_stack_hstack.png)

In [26]:
a1 = np.arange(1, 13)
print(a1)
# > [ 1  2  3  4  5  6  7  8  9 10 11 12]
a2 = np.arange(13, 25)
print(a2)
# > [13 14 15 16 17 18 19 20 21 22 23 24]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[13 14 15 16 17 18 19 20 21 22 23 24]


In [27]:
stack0 = np.stack((a1, a1, a2, a2))  # default stack along 0th axis
print(stack0.shape)
# > (4, 12)
print(stack0)
# > [[ 1  2  3  4  5  6  7  8  9 10 11 12]
#    [ 1  2  3  4  5  6  7  8  9 10 11 12]
#    [13 14 15 16 17 18 19 20 21 22 23 24]
#    [13 14 15 16 17 18 19 20 21 22 23 24]]

(4, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


Stack along the 1st dimension (axis=1)


In [28]:
stack1 = np.stack((a1, a1, a2, a2), axis=1)
print(stack1.shape)
# > (12, 4)
print(stack1)
# > [[ 1  1 13 13]
#    [ 2  2 14 14]
#    [ 3  3 15 15]
#    [ 4  4 16 16]
#    [ 5  5 17 17]
#    [ 6  6 18 18]
#    [ 7  7 19 19]
#    [ 8  8 20 20]
#    [ 9  9 21 21]
#    [10 10 22 22]
#    [11 11 23 23]
#    [12 12 24 24]]

(12, 4)
[[ 1  1 13 13]
 [ 2  2 14 14]
 [ 3  3 15 15]
 [ 4  4 16 16]
 [ 5  5 17 17]
 [ 6  6 18 18]
 [ 7  7 19 19]
 [ 8  8 20 20]
 [ 9  9 21 21]
 [10 10 22 22]
 [11 11 23 23]
 [12 12 24 24]]


In [29]:
stack_long = np.hstack((a1, a2))
print(stack_long.shape)
# > (24,)
print(stack_long)
# > [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

(24,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Create multi-dimensional array (3D)


![3d_from_2d](img/3d_from_2d.png)

In [32]:
a1 = np.arange(1, 13).reshape(3, -1)  # 3_4
a2 = np.arange(13, 25).reshape(3, -1)  # 3_4
print(a1)
# > [[ 1  2  3  4]
#    [ 5  6  7  8]
#    [ 9 10 11 12]]
print(a2)
# > [[13 14 15 16]
#    [17 18 19 20]
#    [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [33]:
a3_0 = np.stack((a1, a2))  # default axis=0 (dimension 0)
a3_1 = np.stack((a1, a2), axis=1)  # along dimension 1
a3_2 = np.stack((a1, a2), axis=2)  # along dimension 2
print(a3_0.shape)
# > (2, 3, 4)
print(a3_1.shape)
# > (3, 2, 4)
print(a3_2.shape)
# > (3, 4, 2)

(2, 3, 4)
(3, 2, 4)
(3, 4, 2)


In [34]:
print(a3_0)
# > [[[ 1  2  3  4]
#     [ 5  6  7  8]
#     [ 9 10 11 12]]

#    [[13 14 15 16]
#     [17 18 19 20]
#     [21 22 23 24]]]
print(a3_1)
# > [[[ 1  2  3  4]
#     [13 14 15 16]]

#    [[ 5  6  7  8]
#     [17 18 19 20]]

#    [[ 9 10 11 12]
#     [21 22 23 24]]]
print(a3_2)
# > [[[ 1 13]
#     [ 2 14]
#     [ 3 15]
#     [ 4 16]]

#    [[ 5 17]
#     [ 6 18]
#     [ 7 19]
#     [ 8 20]]

#    [[ 9 21]
#     [10 22]
#     [11 23]
#     [12 24]]]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]
[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]


In [36]:
print(a1)  # check what's a1
# > [[ 1  2  3  4]
#    [ 5  6  7  8]
#    [ 9 10 11 12]]
# # solutions


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
a3_0[0, :, :]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a3_1[:, 0, :]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
a3_2[:, :, 0]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Flatten multidimensional arrays


使用ravel（）展平多维数组。
下面，我们逐行浏览（默认顺序为“ C”）到一维数组

![flatten](img/flatten_multidimension_array.png)

In [40]:
print(a3_0)
# > [[[ 1  2  3  4]
#     [ 5  6  7  8]
#     [ 9 10 11 12]]

#    [[13 14 15 16]
#     [17 18 19 20]
#     [21 22 23 24]]]
print(a3_0.ravel())
# > [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [41]:
print(a3_0.ravel(order='F'))
# > [ 1 13  5 17  9 21  2 14  6 18 10 22  3 15  7 19 11 23  4 16  8 20 12 24]

[ 1 13  5 17  9 21  2 14  6 18 10 22  3 15  7 19 11 23  4 16  8 20 12 24]


## Reshape multidimensional arrays


In [42]:
# reshape row by row (default order=C) to 2D array
print(a3_0)  # 2_3_4
# > [[[ 1  2  3  4]
#     [ 5  6  7  8]
#     [ 9 10 11 12]]

#    [[13 14 15 16]
#     [17 18 19 20]
#     [21 22 23 24]]]
print(a3_0.reshape(4, -1))  # reshape to 4_6 (row by row)
# > [[ 1  2  3  4  5  6]
#    [ 7  8  9 10 11 12]
#    [13 14 15 16 17 18]
#    [19 20 21 22 23 24]]
print(a3_0.reshape(4, -1, order='F'))  # reshape (column by column)
# > [[ 1  9  6  3 11  8]
#    [13 21 18 15 23 20]
#    [ 5  2 10  7  4 12]
#    [17 14 22 19 16 24]]
print(a3_0.reshape(4, 2, 3))  # reshape to 4_2_3 (row by row)
# > [[[ 1  2  3]
#     [ 4  5  6]]
#    [[ 7  8  9]
#     [10 11 12]]
#    [[13 14 15]
#     [16 17 18]]
#    [[19 20 21]
#     [22 23 24]]]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 1  9  6  3 11  8]
 [13 21 18 15 23 20]
 [ 5  2 10  7  4 12]
 [17 14 22 19 16 24]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
